<svg width="144" height="174" viewBox="0 0 144 174" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M123.404 116.753C123.366 113.407 120.796 110.714 117.674 110.748C114.555 110.783 112.043 113.531 112.08 116.879L112.408 146.454L118.127 152.448L123.732 146.306L123.404 116.753Z" fill="#145E76" class="svg-elem-1"></path>
<path d="M112.197 158.947L116.895 153.798L104.692 141.006C102.87 139.096 99.9392 139.129 98.1597 141.079L96.7026 142.676C94.923 144.626 94.9579 147.766 96.7803 149.677L110.392 163.945C110.335 161.995 111.019 160.238 112.197 158.947Z" fill="#51C3E8" class="svg-elem-2"></path>
<path d="M113.458 160.269C112.6 161.209 112.136 162.458 112.15 163.785C112.177 166.189 113.482 167.214 115.028 168.834C116.85 170.744 119.78 170.712 121.56 168.762L139.407 149.203C141.186 147.253 141.151 144.113 139.329 142.202L137.837 140.638C136.014 138.728 133.084 138.761 131.304 140.711L113.458 160.269Z" fill="#1E7D72" class="svg-elem-3"></path>
</svg>


<style>
/***************************************************
 * Generated by SVG Artista on 8/5/2022, 12:27:34 PM
 * MIT license (https://opensource.org/licenses/MIT)
 * W. https://svgartista.net
 **************************************************/

	

@-webkit-keyframes animate-svg-fill-1 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(20, 94, 118);
  }
}

@keyframes animate-svg-fill-1 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(20, 94, 118);
  }
}

.svg-elem-1 {
  -webkit-animation: animate-svg-fill-1 0.9s cubic-bezier(0.445, 0.05, 0.55, 0.95) 1.2s both;
          animation: animate-svg-fill-1 0.9s cubic-bezier(0.445, 0.05, 0.55, 0.95) 1.2s both;
}

@-webkit-keyframes animate-svg-fill-2 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(81, 195, 232);
  }
}

@keyframes animate-svg-fill-2 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(81, 195, 232);
  }
}

.svg-elem-2 {
  -webkit-animation: animate-svg-fill-2 0.9s cubic-bezier(0.445, 0.05, 0.55, 0.95) 2.3s both;
          animation: animate-svg-fill-2 0.9s cubic-bezier(0.445, 0.05, 0.55, 0.95) 2.3s both;
}

@-webkit-keyframes animate-svg-fill-3 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(30, 125, 114);
  }
}

@keyframes animate-svg-fill-3 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(30, 125, 114);
  }
}

.svg-elem-3 {
  -webkit-animation: animate-svg-fill-3 0.9s cubic-bezier(0.445, 0.05, 0.55, 0.95) 3.4000000000000004s both;
          animation: animate-svg-fill-3 0.9s cubic-bezier(0.445, 0.05, 0.55, 0.95) 3.4000000000000004s both;
}

</style>
